### PR TITLE
Document process of installing go version 1.12

### PR DESCRIPTION
**Pull request by jvasile**
go-orbit-db only works with version 1.12.  For users that are on 1.13
but don't want to roll back system-wide, we can use "go get" to
install an old version of golang.  This is the easiest way to
installing multiple go versions and teaching your system to let them
co-exist.

This patch documents the two needed commands, notes when they are
needed, and informs the user how to use the resulting version 1.12
binary.

### CODE REVIEW

**Comment by jvasile** [comment]
BTW, any plans to make this work with version golang v1.13 and later?

**Comment by glouvigny** [comment]
Hi James, 

Thank you for your PRs, we are indeed considering supporting go 1.13 and @gfanton is doing work related to it (which might conflict with #21).

Thus, at this point we don't plan to document installing an older version of go on the README.md file

**Comment by jvasile** [comment]
That's a good reason to reject this PR.  Shall we close it?

**Comment by glouvigny** [comment]
Before closing this PR (along #21), can you confirm us that you can install and use this lib as expected?

**Pull request closed without merging**
